### ISSUE TITLE
getting error whenever trying to stream through raspberry pi

### ISSUE THREAD

**Issue by yogii786** [soyersoyer/fmp4streamer#4]
ERROR:root:V4L2Camera: can't read SPS and PPS from the first frame

**Comment by soyersoyer** [comment]
Does your camera support h264 format?
You can check with:
`v4l2-ctl --list-formats`

**Comment by yogii786** [comment]
here  I attached screenshot of listed formats could you please check and let me know sugggested camera which support H264 format?
![Screenshot from 2022-01-05 10-31-48](https://user-images.githubusercontent.com/57557160/148163221-951ff632-3289-472b-b017-c662343bf34f.png)

**Comment by yogii786** [comment]
using usb camera IMX291

**Comment by soyersoyer** [comment]
It works with the pi camera boards (with the old camera stack) or any usb uvc camera which supports the h264 format. You can find some here: https://en.everybodywiki.com/List_of_cameras_with_onboard_video_compression

I have already started working on encoding the YUYV format with the V4L2 m2m encoder on the pi. Stay tuned!

**Comment by fcoury** [comment]
Not sure if related, but I am getting this:

Traceback (most recent call last):
  File "/home/pi/fmp4streamer/fmp4streamer.py", line 271, in <module>
    camera = V4L2Camera(device, dict(config.items(device)))
  File "/home/pi/fmp4streamer/v4l2camera.py", line 35, in __init__
    self.init_fps(int(params.get('fps')))
  File "/home/pi/fmp4streamer/v4l2camera.py", line 66, in init_fps
    ioctl(self.fd, v4l2.VIDIOC_S_PARM, parm)
OSError: [Errno 25] Inappropriate ioctl for device

I can stream fine using gst-launch-1.0.

**Comment by fcoury** [comment]
After removing a couple of ioctl calls I am left with the same error:

```
ERROR:root:V4L2Camera: can't read SPS and PPS from the first frame
```

I would also be interested on the YUYV format.

**Comment by yogii786** [comment]
Hi @fcoury could you please share your Gstreamer pipeline so that  I can use that

**Comment by yogii786** [comment]
> 

Imx291 usb camera supports H264 format hence I checked by printing sps and pps there values are 2 and 2 respectively

**Comment by soyersoyer** [comment]
Try the 3.1.0 version and read the Readme for the configuration.

**Comment by soyersoyer** [comment]
@yogii786 Please try the v3.2.0 with the capture_format = MJPGH264 configuration option.

**Comment by soyersoyer** [comment]
Feel free to open, if you have any other questions.
