### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vinsub** [soyersoyer/fmp4streamer#5]
I am so sorry, i have an error running the fmp4streamer.py.

Waiting for the first h264 frame...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Desktop/touchUI/fmp4streamer/v4l2camera.py", line 274, in run
    self.start_capturing()
  File "/home/pi/Desktop/touchUI/fmp4streamer/v4l2camera.py", line 243, in start_capturing
    ioctl(self.fd, v4l2.VIDIOC_STREAMON, struct.pack('I', v4l2.V4L2_BUF_TYPE_VIDEO_CAPTURE))
OSError: [Errno 22] Invalid argument

**Comment by soyersoyer** [comment]
What type of camera do you have? What is your config? OS?

**Comment by Vinsub** [comment]
Sorry for delay, i have e raspberry 4, camera 2.1, Raspbian.
Traceback (most recent call last):
  File "fmp4streamer.py", line 264, in <module>
    camera = V4L2Camera(device, h264parser, config)
  File "/home/pi/Desktop/touchUI/fmp4streamer/fmp4streamer-3.4.1/v4l2camera.py", line 40, in __init__
    self.init_device(width, height, capture_format_real)
  File "/home/pi/Desktop/touchUI/fmp4streamer/fmp4streamer-3.4.1/v4l2camera.py", line 123, in init_device
    ioctl(self.fd, v4l2.VIDIOC_S_FMT, fmt)
OSError: [Errno 16] Device or resource busy
Now i have this error.
Thanks a lot

**Comment by soyersoyer** [comment]
Something is using your camera.

**Comment by Vinsub** [comment]
I dont now, but if i try with another software the camera works

**Comment by soyersoyer** [comment]
Please close the other camera software, only one process can use it.

**Comment by Vinsub** [comment]
i close all software and i reboot system, how can i check if there is a service that uses camera?

**Comment by soyersoyer** [comment]
$ lsof /dev/video0

**Comment by Vinsub** [comment]
This is the results with a software that works with camera:
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python3 681   pi  mem    CHR   81,5           285 /dev/video0
python3 681   pi    3u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi    4u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi    6u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi    8u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi   10u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi   12u   CHR   81,5      0t0  285 /dev/video0
python3 681   pi   14u   CHR   81,5      0t0  285 /dev/video0


raspberrypi
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2022-02-19 13:27:53 CET; 1h 12min ago
   CGroup: /user.slice/user-1000.slice/user@1000.service
           ├─pulseaudio.service
           │ └─790 /usr/bin/pulseaudio --daemonize=no
           ├─gvfs-gphoto2-volume-monitor.service
           │ └─822 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
           ├─dbus.service
           │ └─702 /usr/bin/dbus-daemon --session --address=systemd: --nofork --
           ├─gvfs-udisks2-volume-monitor.service
           │ └─813 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
           ├─gvfs-metadata.service
           │ └─1035 /usr/lib/gvfs/gvfsd-metadata
           ├─gvfs-mtp-volume-monitor.service
           │ └─835 /usr/lib/gvfs/gvfs-mtp-volume-monitor
           ├─gvfs-goa-volume-monitor.service
           │ └─831 /usr/lib/gvfs/gvfs-goa-volume-monitor
           ├─gvfs-afc-volume-monitor.service
           │ └─839 /usr/lib/gvfs/gvfs-afc-volume-monitor
           ├─fmp4streamer.service
           │ └─681 /usr/bin/python3 fmp4streamer.py
           ├─init.scope
           │ ├─572 /lib/systemd/systemd --user
           │ └─588 (sd-pam)
           └─gvfs-daemon.service
             ├─739 /usr/lib/gvfs/gvfsd
             ├─744 /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
             └─853 /usr/lib/gvfs/gvfsd-trash --spawner :1.4 /org/gtk/gvfs/exec_s


raspberrypi
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 1970-01-01 01:00:03 CET; 52 years 1 months ago
   CGroup: /
           ├─user.slice
           │ └─user-1000.slice
           │   ├─session-2.scope
           │   │ ├─ 690 lightdm --session-child 14 17
           │   │ ├─ 694 /usr/bin/lxsession -s LXDE-pi -e LXDE
           │   │ ├─ 728 /usr/bin/ssh-agent x-session-manager
           │   │ ├─ 755 openbox --config-file /home/pi/.config/openbox/lxde-pi-r
           │   │ ├─ 759 lxpolkit
           │   │ ├─ 761 lxpanel --profile LXDE-pi
           │   │ ├─ 762 pcmanfm --desktop --profile LXDE-pi
           │   │ ├─ 767 /usr/bin/ssh-agent -s
           │   │ ├─ 769 xcompmgr -aR
           │   │ ├─ 782 /usr/bin/python3 /usr/share/system-config-printer/applet
           │   │ ├─ 815 /usr/lib/menu-cache/menu-cached /run/user/1000/menu-cach
           │   │ ├─ 974 lxterminal
           │   │ ├─ 980 bash
           │   │ ├─1044 /usr/lib/chromium-browser/chromium-browser-v7 --force-re
           │   │ ├─1065 /usr/lib/chromium-browser/crashpad_handler --monitor-sel
           │   │ ├─1067 /usr/lib/chromium-browser/crashpad_handler --no-periodic
           │   │ ├─1071 /usr/lib/chromium-browser/chromium-browser-v7 --type=zyg
           │   │ ├─1072 /usr/lib/chromium-browser/chromium-browser-v7 --type=zyg
           │   │ ├─1074 /usr/lib/chromium-browser/chromium-browser-v7 --type=zyg
           │   │ ├─1096 /usr/lib/chromium-browser/chromium-browser-v7 --type=gpu
           │   │ ├─1100 /usr/lib/chromium-browser/chromium-browser-v7 --type=uti
           │   │ ├─1108 /usr/lib/chromium-browser/chromium-browser-v7 --type=uti
           │   │ ├─1125 /usr/lib/chromium-browser/chromium-browser-v7 --type=bro
           │   │ ├─1167 /usr/lib/chromium-browser/chromium-browser-v7 --type=ren
           │   │ ├─1332 /usr/lib/chromium-browser/chromium-browser-v7 --type=ren
           │   │ ├─1371 bash
           │   │ ├─1378 sudo geany
           │   │ ├─1379 geany
           │   │ ├─1386 /bin/bash
           │   │ ├─1393 dbus-launch --autolaunch=5f125a1f8b684a668532faebb841133
           │   │ ├─1394 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 
           │   │ ├─1397 /usr/lib/dconf/dconf-service
           │   │ ├─2422 /usr/lib/chromium-browser/chromium-browser-v7 --type=uti
           │   │ ├─2423 /usr/lib/chromium-browser/chromium-browser-v7 --type=uti
           │   │ ├─2463 bash
           │   │ ├─2571 sudo thonny
           │   │ ├─2572 /usr/bin/python3 /usr/bin/thonny
           │   │ ├─2577 /usr/bin/python3 -u -B -m thonny.plugins.cpython /root/D
           │   │ ├─2903 /usr/lib/chromium-browser/chromium-browser-v7 --type=ren
           │   │ ├─3101 /usr/lib/chromium-browser/chromium-browser-v7 --type=ren
           │   │ ├─3117 bash
           │   │ ├─3157 sudo node app.js
           │   │ ├─3158 node app.js
           │   │ ├─3171 /opt/mjpg-streamer/mjpg_streamer -i input_raspicam.so -v
           │   │ ├─3186 python -u test.py
           │   │ ├─3291 systemctl status
           │   │ └─3292 pager
           │   ├─session-3.scope
           │   │ ├─608 /bin/login -f
           │   │ └─851 -bash
           │   └─user@1000.service
           │     ├─pulseaudio.service
           │     │ └─790 /usr/bin/pulseaudio --daemonize=no
           │     ├─gvfs-gphoto2-volume-monitor.service
           │     │ └─822 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
           │     ├─dbus.service
           │     │ └─702 /usr/bin/dbus-daemon --session --address=systemd: --nof
           │     ├─gvfs-udisks2-volume-monitor.service
           │     │ └─813 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
           │     ├─gvfs-metadata.service
           │     │ └─1035 /usr/lib/gvfs/gvfsd-metadata
           │     ├─gvfs-mtp-volume-monitor.service
           │     │ └─835 /usr/lib/gvfs/gvfs-mtp-volume-monitor
           │     ├─gvfs-goa-volume-monitor.service
           │     │ └─831 /usr/lib/gvfs/gvfs-goa-volume-monitor
           │     ├─gvfs-afc-volume-monitor.service
           │     │ └─839 /usr/lib/gvfs/gvfs-afc-volume-monitor
           │     ├─fmp4streamer.service
           │     │ └─681 /usr/bin/python3 fmp4streamer.py
           │     ├─init.scope
           │     │ ├─572 /lib/systemd/systemd --user
           │     │ └─588 (sd-pam)
           │     └─gvfs-daemon.service
           │       ├─739 /usr/lib/gvfs/gvfsd
           │       ├─744 /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_
           │       └─853 /usr/lib/gvfs/gvfsd-trash --spawner :1.4 /org/gtk/gvfs/
           ├─init.scope
           │ └─1 /sbin/init splash
           └─system.slice
             ├─lightdm.service
             │ ├─570 /usr/sbin/lightdm
             │ └─606 /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/ro
             ├─alsa-state.service
             │ └─433 /usr/sbin/alsactl -E HOME=/run/alsa -s -n 19 -c rdaemon
             ├─systemd-timesyncd.service
             │ └─367 /lib/systemd/systemd-timesyncd
             ├─vncserver-x11-serviced.service
             │ ├─548 /usr/bin/vncserver-x11-serviced -fg
             │ ├─569 /usr/bin/vncserver-x11-core -service
             │ ├─677 /usr/bin/vncagent service 15
             │ ├─824 /usr/bin/vncserverui service 16
             │ └─845 /usr/bin/vncserverui -statusicon 5
             ├─dbus.service
             │ └─448 /usr/bin/dbus-daemon --system --address=systemd: --nofork -
             ├─hciuart.service
             │ └─897 /usr/bin/hciattach /dev/serial1 bcm43xx 3000000 flow -
             ├─udisks2.service
             │ └─417 /usr/lib/udisks2/udisksd
             ├─ssh.service
             │ └─583 /usr/sbin/sshd -D
             ├─avahi-daemon.service
             │ ├─443 avahi-daemon: running [raspberrypi.local]
             │ └─465 avahi-daemon: chroot helper
             ├─system-serial\x2dgetty.slice
             │ └─serial-getty@ttyS0.service
             │   └─607 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 tt
             ├─wpa_supplicant.service
             │ └─451 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
             ├─triggerhappy.service
             │ └─413 /usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --so
             ├─systemd-logind.service
             │ └─428 /lib/systemd/systemd-logind
             ├─rtkit-daemon.service
             │ └─797 /usr/lib/rtkit/rtkit-daemon
             ├─cups.service
             │ └─447 /usr/sbin/cupsd -l
             ├─polkit.service
             │ └─542 /usr/lib/policykit-1/polkitd --no-debug
             ├─cron.service
             │ └─414 /usr/sbin/cron -f
             ├─apache2.service
             │ ├─613 /usr/sbin/apache2 -k start
             │ ├─614 /usr/sbin/apache2 -k start
             │ └─615 /usr/sbin/apache2 -k start
             ├─systemd-udevd.service
             │ └─157 /lib/systemd/systemd-udevd
             ├─rsyslog.service
             │ └─420 /usr/sbin/rsyslogd -n -iNONE
             ├─bluetooth.service
             │ └─910 /usr/lib/bluetooth/bluetoothd
             ├─systemd-journald.service
             │ └─119 /lib/systemd/systemd-journald
             ├─rng-tools.service
             │ └─460 /usr/sbin/rngd -r /dev/hwrng
             ├─dhcpcd.service
             │ ├─494 /sbin/dhcpcd -q -b
             │ └─589 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf
             └─cups-browsed.service
               └─543 /usr/sbin/cups-browsed

Ok, i undestand, i'm a idiot.
I made the service of fmp4stream...
Now, 2 questions:
1. How can remove this service from start?
2. I stop the service, now the error is:
ERROR:root:/dev/video0: the capture memory should be MMAP on the last element in the chain
Thanks!!!

**Comment by Vinsub** [comment]
Ok, it works, thank you so match!!!

**Comment by soyersoyer** [comment]
$ systemctl --user disable fmp4streamer

**Comment by Vinsub** [comment]
Thanks!!!

**Comment by soyersoyer** [comment]
You're welcome!
