### ISSUE TITLE
IP Camera Adapter 

### ISSUE THREAD

**Issue by juuiceboxx** [soyersoyer/fmp4streamer#6]
Hello, I have been able to connect to my raspberry pi video via an internet browser and have gotten to watch the video live. However, I am attempting to connect to it with an MJPEG IP camera adapter but I keep getting an error: "Some other HTTP error: 301". I understand this is probably because the MP4Streamer is listening in on the H264 stream, but I was hoping you might have an idea of a work-around or some way to fix this. I apologize if this is a dumb question but I am fairly new to the Raspberry pi game. 
Thank you

**Comment by soyersoyer** [comment]
Hello,
That's great! The project's main goal is to stream to browsers efficiently.
The output is H264, not MJPG, so it won't work with MJPG softwares, sorry. Try that with [ustreamer](https://github.com/pikvm/ustreamer) or [mjpg-streamer](https://github.com/jacksonliam/mjpg-streamer).
