### ISSUE TITLE
ISO 14496

### ISSUE THREAD

**Issue by Stonks3141** [soyersoyer/fmp4streamer#8]
I noticed that you referenced ISO 14496 part 12 and 15 in `bmff.py`. I'm working on a similar project to this one right now. Would you have any recommendations for ways to get these standards, drafts, detailed descriptions, or reference/other implementations? I've only been able to get ISO 14496-12:2003 so far, which is quite outdated judging by page count, and the 2020 edition for 67 € at [evs.ee](https://evs.ee).

**Comment by soyersoyer** [comment]
That comment comes from the [berrymse](https://github.com/thinkski/berrymse/blob/master/bmff.go)
There are implementations in the ffmpeg and gstreamer too.

**Comment by Stonks3141** [comment]
ok, thanks!
